import { type CountryCode } from '../model/types';

export const COUNTRY_CODES: CountryCode[] = [
  { code: '+66', name: 'Thailand', nameKo: '태국', nameTh: 'ไทย' },
  { code: '+82', name: 'South Korea', nameKo: '한국', nameTh: 'เกาหลี' },
  { code: '+1', name: 'United States', nameKo: '미국', nameTh: 'อเมริกา' },
  { code: '+44', name: 'United Kingdom', nameKo: '영국', nameTh: 'อังกฤษ' },
  { code: '+49', name: 'Germany', nameKo: '독일', nameTh: 'เยอรมนี' },
  { code: '+33', name: 'France', nameKo: '프랑스', nameTh: 'ฝรั่งเศส' },
  { code: '+81', name: 'Japan', nameKo: '일본', nameTh: 'ญี่ปุ่น' },
  { code: '+86', name: 'China', nameKo: '중국', nameTh: 'จีน' },
  { code: '+91', name: 'India', nameKo: '인도', nameTh: 'อินเดีย' },
  { code: '+61', name: 'Australia', nameKo: '호주', nameTh: 'ออสเตรเลีย' },
  { code: '+55', name: 'Brazil', nameKo: '브라질', nameTh: 'บราซิล' },
  { code: '+7', name: 'Russia', nameKo: '러시아', nameTh: 'รัสเซีย' },
  { code: '+34', name: 'Spain', nameKo: '스페인', nameTh: 'สเปน' },
  { code: '+39', name: 'Italy', nameKo: '이탈리아', nameTh: 'อิตาลี' },
  { code: '+52', name: 'Mexico', nameKo: '멕시코', nameTh: 'เม็กซิโก' },
  { code: '+31', name: 'Netherlands', nameKo: '네덜란드', nameTh: 'เนเธอร์แลนด์' },
  { code: '+46', name: 'Sweden', nameKo: '스웨덴', nameTh: 'สวีเดน' },
  { code: '+41', name: 'Switzerland', nameKo: '스위스', nameTh: 'สวิตเซอร์แลนด์' },
  { code: '+32', name: 'Belgium', nameKo: '벨기에', nameTh: 'เบลเยียม' },
  { code: '+47', name: 'Norway', nameKo: '노르웨이', nameTh: 'นอร์เวย์' },
  { code: '+45', name: 'Denmark', nameKo: '덴마크', nameTh: 'เดนมาร์ก' },
  { code: '+65', name: 'Singapore', nameKo: '싱가포르', nameTh: 'สิงคโปร์' },
  { code: '+64', name: 'New Zealand', nameKo: '뉴질랜드', nameTh: 'นิวซีแลนด์' },
  { code: '+60', name: 'Malaysia', nameKo: '말레이시아', nameTh: 'มาเลเซีย' },
  { code: '+63', name: 'Philippines', nameKo: '필리핀', nameTh: 'ฟิลิปปินส์' },
  { code: '+62', name: 'Indonesia', nameKo: '인도네시아', nameTh: 'อินโดนีเซีย' },
  { code: '+90', name: 'Turkey', nameKo: '터키', nameTh: 'ตุรกี' },
  { code: '+27', name: 'South Africa', nameKo: '남아프리카', nameTh: 'แอฟริกาใต้' },
  { code: '+20', name: 'Egypt', nameKo: '이집트', nameTh: 'อียิปต์' },
  { code: '+234', name: 'Nigeria', nameKo: '나이지리아', nameTh: 'ไนจีเรีย' },
  { code: '+92', name: 'Pakistan', nameKo: '파키스탄', nameTh: 'ปากีสถาน' },
  { code: '+880', name: 'Bangladesh', nameKo: '방글라데시', nameTh: 'บังกลาเทศ' },
  { code: '+94', name: 'Sri Lanka', nameKo: '스리랑카', nameTh: 'ศรีลังกา' },
  { code: '+98', name: 'Iran', nameKo: '이란', nameTh: 'อิหร่าน' },
  { code: '+972', name: 'Israel', nameKo: '이스라엘', nameTh: 'อิสราเอล' },
  { code: '+966', name: 'Saudi Arabia', nameKo: '사우디아라비아', nameTh: 'ซาอุดีอาระเบีย' },
  {
    code: '+971',
    name: 'United Arab Emirates',
    nameKo: '아랍에미리트',
    nameTh: 'สหรัฐอาหรับเอมิเรตส์',
  },
];
